### PR TITLE
Update changes from 1.3.3

### PR DESCRIPTION
**Pull request by pablomh**

### CODE REVIEW

**Comment by pablomh** [comment]
@jerpelea, should this be the way to go?

**Comment by kholk** [comment]
Yes, this is perfect. It will also automaGically update the PR open on sonyxperiadev with your commits.
Prima has to be in there for wifi to work, of course.

Just one thing: it's early to disable SMD_DEBUG, leave it enabled for now, remove the commit #0470439 please

**Comment by pablomh** [comment]
Done.

I now need a way to test them :)

**Comment by kholk** [comment]
Wait, does it compile?

**Comment by pablomh** [comment]
It fails the same way as it used to fail with your code :(

**Pull request merged**
