### PR TITLE
cpuquiet: rqbalance: fix nr_run threshold for non-hmp socs

### PR DESCRIPTION
**Pull request by Tommy-Geenexus**
* Additionally:
  - Cleanup inclusions
  - Use consistent comment format, spacing and operators
  - Optimize some code paths
  - Improve general code readability

@kholk 
I left some TODO's / FIXME's.
Tell me what you think about them.

This is tested on togari only, needs evaluating on other platforms.

Should we wrap the hmp code in #ifdefs?
I think it's better to use compile time constants.

Also is it ok to use a boot delay? In my opinion this makes sense.

### CODE REVIEW

**Comment by kholk** [comment]
No ifdefs!!! Also, this driver is generic, meaning that the soc_cluster name is wrong. I think cpu_cluster or soc_cluster would be better. 
This driver is supposed to run on all architectures, including multi cluster x86, where you have NUMA nodes (for example). 

As for everything else, looks huge, I think you did a good job. I need to examine it on a PC and I don't know if I can do that today (on vacation!)... Maybe tomorrow! 

Have you got kitakami or any other HMP machine? 
It needs to be tested again on both SMP and HMP!

**Comment by Tommy-Geenexus** [comment]
Alright, i'll update the PR when i'm free again.

I only have a togari, it needs testing on a hmp system, though it should not break anything.

**Comment by kholk** [comment]
Indeed. I'll examine it on a PC asap!

**Comment by Tommy-Geenexus** [comment]
Thanks, no stress, enjoy ypur vacation!

**Comment by Tommy-Geenexus** [comment]
@kholk 
Patch is rebased. I think this is fine now.
About the return value checking in the threshold store function, it'd be better if you'd input what limits you'd like to have set.

**Pull request closed without merging**
